# Generated by Django 4.0.5 on 2022-06-26 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Studentbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_app.department')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_app.role')),
                ('wing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_app.wings')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_reason', models.CharField(max_length=250)),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_app.equipement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_app.studentbody')),
                ('wing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='final_app.wings')),
            ],
        ),
    ]
