# Generated by Django 4.0.5 on 2022-06-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
